application: tekinme
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: "1.1.7"

handlers:
- url: /static
  static_dir: static
- url: /rot13
  script: rot13.app
- url: /birthday
  script: birthday_validation.app
- url: /thanks
  script: birthday_validation.app
- url: /
  script: main.app
- url: /signup
  script: signup.app
- url: /welcome
  script: signup.app
- url: /blog/*
  script: blog.app
- url: /blog/newpost
  script: blog.app
- url: /blog.json
  script: blog.app
- url: /login
  script: signup.app
- url: /logout
  script: signup.app
- url: /blog/([0-9]+)(?:.json)?
  script: blog.app



